INSERT INTO tb_produto (nome, descricao, preco, quantidade) VALUES
    ('Cabo Életrico de Cobre', '100m de cabo elétrico 1.5mm feito de cobre', 150, 200),
    ('Cabo de Rede', '50m de cabo de rece RJ45', 60, 100),
    ('Pacote de Conectores', 'pacote de 20 conectores para fios elétricos', 30, 200),
    ('Eletroduto de Alumínio', '30m de eletroduto feito de alumínio', 60, 50),
    ('Eletroduto Inox', '30m de eletroduto feito de aço inox', 80, 40),
    ('Eltroduto Flexível', '50m de eletroduto 3cm flexível ', 30, 60),
    ('Eletroduto Flexível Reforçado', '50m de eltroduto 3cm fléxivel reforçado', 50, 60),
    ('Tomada Simples', 'tomada única de 3 pinos', 15, 20),
    ('Tomada Dupla', 'tomada dupla de 3 pinos', 20, 30),
    ('Tomada Tripla', 'tomada tripla de 3 pinos', 25, 40),
    ('Tomada com Interuptor', 'tomada única de 3 pinos com interuptor', 20, 40),
    ('Interruptor Simples', 'interruptor elétrico único', 15, 30),
    ('Interruptor Dimmer', 'interruptor eletrônico', 40, 50),
    ('Lâmpada LED Bulbo', 'lâmpada LED branca formato bulbo 15W', 20, 30),
    ('Lâmpada LED Painel', 'painel LED branco 25W', 40, 30),
    ('Spot LED', 'spot LED 5W', 15, 20),
    ('Refletor LED', 'refletor LED 200W', 60, 14),
    ('Fita LED', 'fita LED branco 5m de comprimento com fonte 12V 5A', 30, 23),
    ('Fita LED RGB', 'fita LED RGB 5m com fonte e controle', 40, 18),
    ('Lâmpada Fluorescente', 'lampada fluorescente comum 15W', 20, 20),
    ('Lâmpada Espiral', 'lampada fluorescente em formato espiral 15W', 25, 25),
    ('Lâmpada Tubo', 'lampada fluorescente em formato tubo 15W', 20, 10),
    ('Lâmpada Luz Negra', 'lâmpada ultravioleta 36W', 50, 8),
    ('Disjuntor Monopolar', 'disjuntor monopolar 20A', 10, 17),
    ('Disjuntor Bipolar', 'disjuntor bipolar 40A', 30, 16),
    ('Disjuntor Tripolar', 'disjuntor tripolar 40A', 50, 18),
    ('Fusíveis de Vidro', 'kit 10 fusíveis de vidro 250V pequeno', 8, 24),
    ('Fusíveis de Cerâmica', 'kit 100 fusíveis de cerâmica 20A', 60, 28),
    ('Fusível Automotivo', 'kit 10 peças fusíveis automotivos 5A', 10, 23),
    ('Quadro de Distribução', 'quadro de distribuição para 8 disjuntores', 50, 16),
    ('Alicate Inox', 'alicate feito de aço inox', 23, 35),
    ('Alicate Desencapador', 'alicate de aço inox para desencapar fios', 40, 38),
    ('Alicate Prensa Terminal', 'alicate de aço inox para preensar terminal elétricos', 55, 33),
    ('Alicate Multiuso', 'alicate de aço inox com mutiplas funções', 30, 20),
    ('Luva Emborachada', 'luva de proteção emborachada', 15, 20),
    ('Voltímetro', '100m de cabo elétrico 3mm feito de cobre ', 20, 28),
    ('Amperímetro', '100m de cabo elétrico 3mm feito de cobre ', 25, 26),
    ('Wattímetro', '100m de cabo elétrico 3mm feito de cobre ', 28, 11),
    ('Multímetro', '100m de cabo elétrico 3mm feito de cobre ', 40, 34),
    ('Sensor de Iluminação', '100m de cabo elétrico 3mm feito de cobre ', 10, 28),
    ('Microcontrolador', 'micontrolador placa raspberry pi 3', 200, 39);

INSERT INTO tb_categoria (nome) VALUES
    ('Cabos'),
    ('Eletrodutos'),
    ('Tomadas'),
    ('Interruptores'),
    ('Iluminação'),
    ('Dispositivos de Proteção'),
    ('Ferramentas'),
    ('Eletrônica');

INSERT INTO tb_produto_categoria (id_produto, id_categoria) VALUES
    (1, 1),
    (2, 1),
    (3, 1),
    (4, 2),
    (5, 2),
    (6, 2),
    (7, 2),
    (8, 3),
    (9, 3),
    (10, 3),
    (11, 3),
    (11, 4),
    (12, 4),
    (13, 4),
    (13, 8),
    (14, 5),
    (15, 5),
    (16, 5),
    (17, 5),
    (18, 5),
    (19, 5),
    (19, 8),
    (20, 5),
    (21, 5),
    (22, 5),
    (23, 5),
    (24, 6),
    (25, 6),
    (26, 6),
    (27, 6),
    (28, 6),
    (29, 6),
    (31, 7),
    (32, 7),
    (33, 7),
    (34, 7),
    (35, 7),
    (36, 7),
    (37, 7),
    (38, 7),
    (39, 7),
    (40, 8),
    (41, 8);