@URL=http://localhost/api

@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tZSI6IkpvXHUwMGUzbyIsImVtYWlsIjoiam9hb0BleGFtcGxlLmNvbSIsIm5hc2NpbWVudG8iOiIxOTkwLTAxLTAxIiwiYWRtaW4iOjF9.Ldgx-ud3bStSd6HAAnjsUVNZFsovbnAj25VasnUKWTw
@JWT2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tZSI6Ik1hcmlhIiwiZW1haWwiOiJtYXJpYUBleGFtcGxlLmNvbSIsIm5hc2NpbWVudG8iOiIxOTkyLTA1LTE1IiwiYWRtaW4iOjB9.biimT5uZ-6DSAvrngnoaibH3KCf9U1Dd60JszTWy2UU

###Get
GET {{URL}}/produto/get.php?categoria=Dispositivos de Proteção

###Put
POST {{URL}}/produto/put.php
Authorization: {{JWT}}
Content-Type: application/json

{
    "nome": "produto A",
    "descricao": "conduz mais",
    "preco": "300",
    "quantidade": "100",
    "categorias": ["alpha"]
}


###Create
POST {{URL}}/produto/create.php
Authorization: {{JWT}}
Content-Type: application/json

{
    "nome": "produto C",
    "descricao": "cabo azul",
    "preco": "100",
    "quantidade": "100",
    "categorias": ["Cabos"]
}

###Delete
GET {{URL}}/produto/delete.php?id=3
Authorization: {{JWT}}